name: sync_to_bitbucket

on:
  push:
    branches: [main]

jobs:
  sync_to_bitbucket:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Bitbucket
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.BITBUCKET_SSH_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:WinterPu/PyUnrealBuildSystem.git
          destination-repo: ssh://git@git.agoralab.co/aduc/pyunrealbuildsystem.git

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.BITBUCKET_SSH_PRIVATE_KEY }}

      - name: Clone target repository
        run: |
          git clone ssh://git@git.agoralab.co/aduc/pyunrealbuildsystem.git target-repo
          cd target-repo
          git submodule init
          git submodule update --recursive

      - name: Update Submodule URL
        run: |
          cd target-repo
          git submodule set-url Config ssh://git@git.agoralab.co/aduc/agoraunrealbuildconfigrepo.git
          git submodule update --remote Config
          git add .
          git commit -m "Update Config submodule URL to repository" || echo "No changes to commit"
          git push origin main
